
spring.application.name=Project-Salary-Management

server.port=8080

# ==========================================
# MySQL Database Configuration
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/salary_management

spring.datasource.username=root
spring.datasource.password=root

# ==========================================
# JPA / Hibernate
# ==========================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Hibernate Batch Configuration
# ==========================================

spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ==========================================
# JSON Date Configuration
# ==========================================

spring.jackson.serialization.write-dates-as-timestamps=false